### ISSUE TITLE
Incorrect token location in 'Rebuild tokens article'

### ISSUE THREAD

**Issue by Bolt10000** [MicrosoftDocs/SupportArticles-docs#88]
https://github.com/MicrosoftDocs/SupportArticles-docs/blob/main/support/windows-server/deployment/rebuild-tokens-dotdat-file.md

That page lists incorrect locations, correct locations are,

```
"%Systemdrive%\Windows\System32\spp\store_test\2.0\tokens.dat"
"%Systemdrive%\Windows\System32\spp\store\2.0\tokens.dat"
"%Systemdrive%\Windows\System32\spp\store\tokens.dat"
"%Systemdrive%\Windows\ServiceProfiles\NetworkService\AppData\Roaming\Microsoft\SoftwareProtectionPlatform\tokens.dat"
```
Where first is for Windows 10 insiders, 2nd is for Windows 10, 3rd is for Windows 8, 4rth is for Windows 7.

**Comment by Deland-Han** [comment]
Thank you for the feedback. @Bolt10000.

I checked and found there are spaces missing in the commands. I have corrected them and they should work now.

**Comment by WindowsAddict** [comment]
> Thank you for the feedback. @Bolt10000.
> 
> I checked and found there are spaces missing in the commands. I have corrected them and they should work now.

@Deland-Han 
Windows 8.1 token location is still incorrect, 
correct is,
`"%Systemdrive%\Windows\System32\spp\store\tokens.dat"`
Please check and fix. thanks.

**Comment by Bolt10000** [comment]
> Thank you for the feedback. @Bolt10000.
> 
> I checked and found there are spaces missing in the commands. I have corrected them and they should work now.

@Deland-Han
Windows 8.1 token location is still incorrect,
correct is,
"%Systemdrive%\Windows\System32\spp\store\tokens.dat"
Please check and fix. thanks.
